<a href="https://colab.research.google.com/github/imrazack-cisco/bits/blob/main/Gram%20Scmidth%20Module%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import sympy as sp
from scipy.linalg import lu, cholesky, eigh

# Example 3x3 matrix
matrix = np.array([[4, 1, 3], [1, 5, 1], [3, 1, 6]])

# 1. Gram-Schmidt Process
def gram_schmidt(mat):
    mat = np.array(mat, dtype='float64')
    Q, R = np.linalg.qr(mat)
    return Q, R

# 2. LU Decomposition
def lu_decomposition(mat):
    P, L, U = lu(mat)
    return P, L, U

# 3. Cholesky Decomposition (only for symmetric positive definite matrices)
def cholesky_decomposition(mat):
    try:
        L = cholesky(mat, lower=True)
        return L
    except np.linalg.LinAlgError:
        return "Matrix is not positive definite."

# 4. Characteristic Polynomial
def characteristic_polynomial(mat):
    M = sp.Matrix(mat)
    return M.charpoly().as_expr()

# 5. Eigenvalues and Eigenvectors
def eigenvalues_eigenvectors(mat):
    eigenvalues, eigenvectors = np.linalg.eig(mat)
    return eigenvalues, eigenvectors

# 6. Spectral Theorem (Eigen decomposition for symmetric matrices)
def spectral_decomposition(mat):
    if np.allclose(mat, mat.T):
        eigenvalues, eigenvectors = eigh(mat)
        return eigenvalues, eigenvectors
    else:
        return "Matrix is not symmetric, spectral theorem does not apply."

# 7. Hermitian Matrix Check (Conjugate transpose equals the matrix)
def is_hermitian(mat):
    return np.allclose(mat, np.conjugate(mat.T))

# Example usage:
print("Matrix:")
print(matrix)

# 1. Gram-Schmidt Process
Q, R = gram_schmidt(matrix)
print("\nGram-Schmidt Process:")
print("Q matrix (orthogonal vectors):")
print(Q)
print("R matrix (upper triangular):")
print(R)

# 2. LU Decomposition
P, L, U = lu_decomposition(matrix)
print("\nLU Decomposition:")
print("P matrix (permutation matrix):")
print(P)
print("L matrix (lower triangular matrix):")
print(L)
print("U matrix (upper triangular matrix):")
print(U)

# 3. Cholesky Decomposition
L = cholesky_decomposition(matrix)
print("\nCholesky Decomposition (L matrix):")
print(L)

# 4. Characteristic Polynomial
char_poly = characteristic_polynomial(matrix)
print("\nCharacteristic Polynomial of the matrix:")
print(char_poly)

# 5. Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = eigenvalues_eigenvectors(matrix)
print("\nEigenvalues and Eigenvectors:")
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

# 6. Spectral Theorem (For symmetric matrices)
spectral = spectral_decomposition(matrix)
print("\nSpectral Decomposition (for symmetric matrices):")
print(spectral)

# 7. Hermitian Matrix Check
print("\nIs the matrix Hermitian?")
print(is_hermitian(matrix))


Matrix:
[[4 1 3]
 [1 5 1]
 [3 1 6]]

Gram-Schmidt Process:
Q matrix (orthogonal vectors):
[[-0.78446454  0.18264968 -0.59266726]
 [-0.19611614 -0.97966645 -0.04233338]
 [-0.58834841  0.08302258  0.80433414]]
R matrix (upper triangular):
[[-5.09901951 -2.35339362 -6.07960019]
 [ 0.         -4.63265998  0.06641806]
 [ 0.          0.          3.00566967]]

LU Decomposition:
P matrix (permutation matrix):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L matrix (lower triangular matrix):
[[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.75       0.05263158 1.        ]]
U matrix (upper triangular matrix):
[[4.         1.         3.        ]
 [0.         4.75       0.25      ]
 [0.         0.         3.73684211]]

Cholesky Decomposition (L matrix):
[[2.         0.         0.        ]
 [0.5        2.17944947 0.        ]
 [1.5        0.11470787 1.93309133]]

Characteristic Polynomial of the matrix:
lambda**3 - 15*lambda**2 + 63*lambda - 71

Eigenvalues and Eigenvectors:
Eigenval