<a href="https://colab.research.google.com/github/imrazack-cisco/bits/blob/main/Matrix%20Module%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sympy as sp

# Example 3x3 matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# 1. Matrix Addition
def matrix_addition(mat1, mat2):
    return np.add(mat1, mat2)

# 2. Matrix Multiplication
def matrix_multiplication(mat1, mat2):
    return np.dot(mat1, mat2)

# 3. Matrix Transpose
def matrix_transpose(mat):
    return np.transpose(mat)

# 4. Determinant
def matrix_determinant(mat):
    return np.linalg.det(mat)

# 5. Matrix Inverse
def matrix_inverse(mat):
    try:
        return np.linalg.inv(mat)
    except np.linalg.LinAlgError:
        return "Matrix is singular and does not have an inverse."

# 6. Gaussian Elimination (Row Echelon Form - REF)
def row_echelon_form(mat):
    M = sp.Matrix(mat)
    return M.echelon_form()

# 7. Reduced Row Echelon Form (RREF)
def reduced_row_echelon_form(mat):
    M = sp.Matrix(mat)
    return M.rref()

# 8. Rank of the Matrix
def matrix_rank(mat):
    return np.linalg.matrix_rank(mat)

# Example matrix1 and matrix2 for testing
print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

# 1. Addition
print("\nMatrix Addition:")
print(matrix_addition(matrix1, matrix2))

# 2. Multiplication
print("\nMatrix Multiplication:")
print(matrix_multiplication(matrix1, matrix2))

# 3. Transpose
print("\nTranspose of Matrix 1:")
print(matrix_transpose(matrix1))

# 4. Determinant of Matrix 1
print("\nDeterminant of Matrix 1:")
print(matrix_determinant(matrix1))

# 5. Inverse of Matrix 1
print("\nInverse of Matrix 1:")
print(matrix_inverse(matrix1))

# 6. REF of Matrix 1
print("\nRow Echelon Form (REF) of Matrix 1:")
print(row_echelon_form(matrix1))

# 7. RREF of Matrix 1
print("\nReduced Row Echelon Form (RREF) of Matrix 1:")
print(reduced_row_echelon_form(matrix1))

# 8. Rank of Matrix 1
print("\nRank of Matrix 1:")
print(matrix_rank(matrix1))


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of Matrix 1:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant of Matrix 1:
0.0

Inverse of Matrix 1:
Matrix is singular and does not have an inverse.

Row Echelon Form (REF) of Matrix 1:
Matrix([[1, 2, 3], [0, -3, -6], [0, 0, 0]])

Reduced Row Echelon Form (RREF) of Matrix 1:
(Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]]), (0, 1))

Rank of Matrix 1:
2
