<a href="https://colab.research.google.com/github/imrazack-cisco/bits/blob/main/Vectors%20Module%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import sympy as sp

# Example 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Example vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# 1. Linear Independence: A set of vectors is linearly independent if the determinant of the matrix formed by them is non-zero
def linear_independence(mat):
    return np.linalg.matrix_rank(mat) == mat.shape[1]

# 2. Basis: The columns of a matrix form a basis if they are linearly independent
def find_basis(mat):
    M = sp.Matrix(mat)
    return M.columnspace()

# 3. Dimension of a vector space: The dimension is the number of vectors in the basis
def vector_space_dimension(mat):
    return np.linalg.matrix_rank(mat)

# 4. Rank-Nullity Theorem: Rank(A) + Nullity(A) = n (where n is the number of columns)
def rank_nullity_theorem(mat):
    rank = np.linalg.matrix_rank(mat)
    nullity = mat.shape[1] - rank
    return rank, nullity

# 5. Norm (Euclidean norm by default)
def norm(vector, p=2):
    return np.linalg.norm(vector, ord=p)

# 6. Inner Product
def inner_product(v1, v2):
    return np.dot(v1, v2)

# 7. Symmetric Positive Definite Matrix: A symmetric matrix with all positive eigenvalues
def is_symmetric_positive_definite(mat):
    return np.all(np.linalg.eigvals(mat) > 0) and np.allclose(mat, mat.T)

# 8. Length of a vector (Euclidean norm)
def vector_length(vector):
    return np.linalg.norm(vector)

# 9. Distance between two vectors
def vector_distance(v1, v2):
    return np.linalg.norm(v1 - v2)

# 10. Cauchy-Schwarz Inequality: |<v1, v2>| <= ||v1|| * ||v2||
def cauchy_schwarz_inequality(v1, v2):
    return abs(np.dot(v1, v2)) <= np.linalg.norm(v1) * np.linalg.norm(v2)

# 11. Angle between two vectors (using inner product)
def angle_between_vectors(v1, v2):
    cos_theta = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
    return np.arccos(np.clip(cos_theta, -1.0, 1.0))

# 12. Orthogonality: Two vectors are orthogonal if their dot product is 0
def is_orthogonal(v1, v2):
    return np.dot(v1, v2) == 0

# 13. Orthonormal Matrix: A matrix is orthonormal if its columns are orthonormal vectors
def is_orthonormal(mat):
    I = np.eye(mat.shape[0])
    return np.allclose(np.dot(mat.T, mat), I)

# 14. Metric Space (Check if a function satisfies the metric space properties: non-negativity, identity, symmetry, triangle inequality)
def is_metric_space(d, v1, v2, v3):
    return (d(v1, v2) >= 0 and d(v1, v2) == 0 if np.allclose(v1, v2) else True and
            d(v1, v2) == d(v2, v1) and
            d(v1, v3) <= d(v1, v2) + d(v2, v3))

# Example usage:

print("Matrix:")
print(matrix)

# 1. Linear Independence
print("\nAre the vectors linearly independent?")
print(linear_independence(matrix))

# 2. Basis
print("\nBasis of the column space:")
print(find_basis(matrix))

# 3. Dimension of the vector space
print("\nDimension of the vector space:")
print(vector_space_dimension(matrix))

# 4. Rank-Nullity Theorem
rank, nullity = rank_nullity_theorem(matrix)
print("\nRank and Nullity of the matrix:")
print(f"Rank: {rank}, Nullity: {nullity}")

# 5. Norm of vector1
print("\nNorm of vector1:")
print(norm(vector1))

# 6. Inner Product of vector1 and vector2
print("\nInner product of vector1 and vector2:")
print(inner_product(vector1, vector2))

# 7. Symmetric Positive Definite
print("\nIs the matrix symmetric and positive definite?")
print(is_symmetric_positive_definite(matrix))

# 8. Length of vector1
print("\nLength of vector1:")
print(vector_length(vector1))

# 9. Distance between vector1 and vector2
print("\nDistance between vector1 and vector2:")
print(vector_distance(vector1, vector2))

# 10. Cauchy-Schwarz Inequality
print("\nDoes Cauchy-Schwarz inequality hold?")
print(cauchy_schwarz_inequality(vector1, vector2))

# 11. Angle between vector1 and vector2
print("\nAngle between vector1 and vector2 (in radians):")
print(angle_between_vectors(vector1, vector2))

# 12. Orthogonality of vector1 and vector2
print("\nAre vector1 and vector2 orthogonal?")
print(is_orthogonal(vector1, vector2))

# 13. Orthonormal matrix
print("\nIs the matrix orthonormal?")
print(is_orthonormal(matrix))

# 14. Metric space properties
print("\nDoes the Euclidean distance satisfy the metric space properties?")
print(is_metric_space(vector_distance, vector1, vector2, np.array([0, 0, 0])))


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Are the vectors linearly independent?
False

Basis of the column space:
[Matrix([
[1],
[4],
[7]]), Matrix([
[2],
[5],
[8]])]

Dimension of the vector space:
2

Rank and Nullity of the matrix:
Rank: 2, Nullity: 1

Norm of vector1:
3.7416573867739413

Inner product of vector1 and vector2:
32

Is the matrix symmetric and positive definite?
False

Length of vector1:
3.7416573867739413

Distance between vector1 and vector2:
5.196152422706632

Does Cauchy-Schwarz inequality hold?
True

Angle between vector1 and vector2 (in radians):
0.2257261285527342

Are vector1 and vector2 orthogonal?
False

Is the matrix orthonormal?
False

Does the Euclidean distance satisfy the metric space properties?
True
